
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockwatch?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generated-ddl: true
    show-sql: true
    hibernate:
      ddl_auto: update

server:
  port: 8000

